# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxbot', '0002_auto_20170606_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wx_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('group_count', models.CharField(max_length=200)),
                ('use_time', models.DateTimeField(auto_now_add=True)),
                ('group_own', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='wx_account',
            name='use_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
