# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxbot', '0003_auto_20170606_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wx_group',
            name='group_count',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
