# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxbot', '0005_wx_group_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wx_group',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
