# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxbot', '0006_auto_20170608_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_user',
            old_name='join_time',
            new_name='friend_time',
        ),
        migrations.AddField(
            model_name='group_user',
            name='group_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
