# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxbot', '0007_auto_20170608_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='wx_account',
            name='Welcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wx_group',
            name='Welcome',
            field=models.TextField(blank=True, null=True),
        ),
    ]
