# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxbot', '0008_auto_20170609_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='wx_group',
            name='online',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
