# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxbot', '0009_wx_group_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cron_msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_name', models.CharField(max_length=20)),
                ('msg_group', models.CharField(blank=True, max_length=200, null=True)),
                ('msg_content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
