# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wxbot', '0010_cron_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='cron_msg',
            name='msg_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
