# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxbot', '0012_auto_20170615_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cron_msg',
            name='msg_type',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
