# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxbot', '0013_auto_20170615_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cron_msg',
            name='msg_type',
        ),
    ]
