# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxbot', '0015_cron_msg_msg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wx_account',
            name='online',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
