# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxbot', '0016_wx_account_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cron_msg',
            name='msg_type',
            field=models.CharField(default='txt', max_length=20),
        ),
    ]
